---
title: "samply_shiny_code"
author: "Lydia Bleifuss"
date: "2/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

From Allison Shiny Video:

#####################################################################
APP 1

# Attach necessary packages
library(shiny)
library(tidyverse)
library(shinythemes)

# Create the user interface:
ui <- navbarPage("A navigation bar!",
                 theme = shinytheme("cyborg"),
                 tabPanel("FIRST",
                          h1("Some text in my first tab yay"),
                          p("Then some normal text..."),
                          plotOutput(outputId = "diamond_plot")
                          ),
                 tabPanel("SECOND",
                            sidebarLayout(
                            sidebarPanel("Some text!",
                                         checkboxGroupInput("diamondclarity", "Choose diamond clarity", choices = c(levels(diamonds$clarity))
                                                      )
                                         ),
                            mainPanel(plotOutput(outputId = "diamond_plot_2"))
                            )
                          ),
                 tabPanel("Wooooo!"
                          )
                 )

# Create the server:
server <- function(input, output) {

  diamond_clarity <- reactive({

    diamonds %>%
      filter(clarity %in% input$diamondclarity)

  })

  output$diamond_plot <- renderPlot({
    ggplot(data = diamonds, aes(x = carat, y = price)) +
    geom_point(aes(color = clarity))
  })

  output$diamond_plot_2 <- renderPlot({

    ggplot(data = diamond_clarity(), aes(x = clarity, y = price)) +
      geom_violin(aes(fill = clarity))

  })

}

# Combine them into an app:
shinyApp(ui = ui, server = server)

#####################################################################
APP 2

library(shiny)
library(shinydashboard)
library(tidyverse)

ui <- dashboardPage(
  dashboardHeader(title = "Star Wars!"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Homeworld", tabName = "homes", icon = icon("jedi")),
      menuItem("Species", tabName = "species", icon = icon("pastafarianism"))
    )
  ),
  dashboardBody(
    tabItems(
    tabItem(
      tabName = "homes",
      fluidRow(
        box(title = "Homeworld Graph",
            selectInput("sw_species",
                        "Choose species to explore homeworlds:",
                        choices = c(unique(starwars$species)))),
        box(plotOutput(outputId = "sw_plot"))
      )
    ),
    tabItem(
      tabName = "species",
      fluidRow(
        box(title = "HELLO!")
      )
    )

)
)
)

server <- function(input, output) {

  species_df <- reactive({
    starwars %>%
      filter(species == input$sw_species)
  })

  output$sw_plot <- renderPlot({
    ggplot(species_df(), aes(x = homeworld)) +
      geom_bar() +
      coord_flip()
  })

}

shinyApp(ui = ui, server = server)

#####################################################################
APP 3

# Pound sign in front of any non code in RScripts

# My first app example! 
# L-Train


# Attach packages
library(here)
library(shiny)
library(tidyverse)

# Get penguins.csv data
penguins <- read_csv(here("session_4_ex_1", "penguins.csv"))


# Creat 'ui' = "User Interface"

ui <- fluidPage(
  titlePanel("This is  my app title"), 
  sidebarLayout(
    sidebarPanel("Here are my widgets!", 
                 radioButtons(inputId = "species",
                              label = "Choose penguin species:",
                              choices = c("Adelie", "Gentoo", "Awesome Chinstrap Penguins" = "Chinstrap")),
                 selectInput(inputId = "pt_color",
                             label = "Select a point color!",
                             choices = c("Favorite RED!!!" = "red", 
                                         "Pretty purple" = "purple",
                                         "ORAAAAANGE!" = "orange"))),
    mainPanel("Here is my graph!", 
              plotOutput(outputId = "penguin_plot"))
  )
)

# Create a 'server' (takes inputs (user selected) and sends back outputs (which user can see)

server <- function(input, output) {
  
  # Created a reative data frame: 
  penguin_select <- reactive({
    penguins %>% 
      filter(sp_short == input$species)
  })
  
  output$penguin_plot <- renderPlot({
    
    ggplot(data = penguin_select(), aes(x = flipper_length_mm, y = body_mass_g)) +
      geom_point(color = input$pt_color)
    
  })
  
}

# Let R know that you want to combine the ui & server into an app:

shinyApp(ui = ui, server = server)

#####################################################################
APP 4

## Second example from video!!

library(shiny)
library(tidyverse)
library(shinythemes)
library(here)

ui <- navbarPage("Allison's navigation bar!",
                 theme = shinytheme("cyborg"),
                 tabPanel("First tab!", 
                          h1("Some giant text"),
                          p("Here's some regular text..."),
                          plotOutput(outputId = "diamond_plot")),
                 tabPanel("Second tab!",
                          sidebarLayout(
                            sidebarPanel("Some text!",
                                         checkboxGroupInput(inputId = "diamondclarity",
                                                            "Choose some!",
                                                            choices = c(levels(diamonds$clarity)))),
                            mainPanel("Main panel text.",
                                      plotOutput(outputId = "diamond_plot_2"))
                          ))
                 )



server <- function(input, output) {
  
  diamond_clarity <- reactive({
    diamonds %>% 
      filter(clarity %in% input$diamondclarity)
  })
  
  output$diamond_plot <- renderPlot({
    ggplot(data = diamonds, aes(x = carat, y = price)) +
      geom_point(aes(color = clarity))
  })
  
  
  output$diamond_plot_2 <- renderPlot({
    ggplot(data = diamond_clarity(), aes(x = clarity, y = price)) +
      geom_violin(aes(fill = clarity))
  })
  
  
}


shinyApp(ui = ui, server = server)

########################

APP 5

library(shiny)
library(shinydashboard)
library(tidyverse)


ui <- dashboardPage(
  dashboardHeader(title = "Star Wars"), 
  dashboardSidebar(
    sidebarMenu(
      menuItem("Homeworld", tabName = "homes", icon = icon("jedi")),
      menuItem("Species", tabName = "species", icon = icon("pastafarianism"))
    )
  ),
  dashboardBody(
    tabItems(
      tabItem(
        tabName = "homes",
        fluidRow(
          box(title = "Homeworld Graph", 
              selectInput("sw_species", "Choose species:", choices = c(unique(starwars$species)))),
          box(plotOutput(outputId = "sw_plot"))
        )
      )
    )
  )
)


server <- function(input, output) {
  
  species_df <- reactive({
    starwars %>% 
      filter(species == input$sw_species)
  })
  
  output$sw_plot <- renderPlot({
    ggplot(data = species_df(), aes(x = homeworld)) +
      geom_bar() + 
      coord_flip()
  })
  
}


shinyApp(ui = ui, server = server)

#####################################################################

